<a href="https://colab.research.google.com/github/521sai/Pandas_Library/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


# New Section

In [2]:
list=[10,20,30,40]
np.array(list)

array([10, 20, 30, 40])

In [3]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
data=pd.Series(list)
data

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
labels = ['a' ,'b', 'c','d']
sai=pd.Series(data=list, index=labels)
sai

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
ser1 =pd.Series([1,2,3,4], index=['sai','ramu','kumar','sodhi'])
ser2 =pd.Series([2,3,4,1],index=['kavi','sam','ravi','keke'])

In [7]:
ser1

sai      1
ramu     2
kumar    3
sodhi    4
dtype: int64

In [8]:
ser2

kavi    2
sam     3
ravi    4
keke    1
dtype: int64

In [9]:
ser1.values

array([1, 2, 3, 4])

In [10]:
ser2.values

array([2, 3, 4, 1])

In [11]:
ser1.index[0]

'sai'

In [12]:
ser2['keke']

1

In [13]:
ser1.append(ser2)

<ipython-input-13-fced70fb11a8>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser1.append(ser2)


sai      1
ramu     2
kumar    3
sodhi    4
kavi     2
sam      3
ravi     4
keke     1
dtype: int64

In [14]:
ser1+ser2

kavi    NaN
keke    NaN
kumar   NaN
ramu    NaN
ravi    NaN
sai     NaN
sam     NaN
sodhi   NaN
dtype: float64

In [15]:
ser1

sai      1
ramu     2
kumar    3
sodhi    4
dtype: int64

In [16]:
df1 = {'names':['sai','chandu','kavi','king'],'year':[2022,2031,2001,2000]}
pd.DataFrame(df1)

names  year
0     sai  2022
1  chandu  2031
2    kavi  2001
3    king  2000

In [17]:
pd.DataFrame(df1, index=['row1','row2','row3','row4'])

names  year
row1     sai  2022
row2  chandu  2031
row3    kavi  2001
row4    king  2000

In [18]:
np.random.seed(2)
df=pd.DataFrame(np.random.randn(5,5))
df

0         1         2         3         4
0 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
1 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
2  0.551454  2.292208  0.041539 -1.117925  0.539058
3 -0.596160 -0.019130  1.175001 -0.747871  0.009025
4 -0.878108 -0.156434  0.256570 -0.988779 -0.338822

In [19]:
np.random.seed(2)
df3=pd.DataFrame(np.random.randn(5,5), index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4','col5'])
df3

col1      col2      col3      col4      col5
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822

In [20]:
df3['col4']

row1    1.640271
row2   -1.057952
row3   -1.117925
row4   -0.747871
row5   -0.988779
Name: col4, dtype: float64

In [21]:
df3.values

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801,  0.04153939, -1.11792545,  0.53905832],
       [-0.5961597 , -0.0191305 ,  1.17500122, -0.74787095,  0.00902525],
       [-0.87810789, -0.15643417,  0.25657045, -0.98877905, -0.33882197]])

In [22]:
df3.index[1]

'row2'

Adding Columns

In [23]:
df3['Add'] = df3['col1'] + df3['col2']
df3

col1      col2      col3      col4      col5       Add
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436 -0.473025
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008 -0.338866
row3  0.551454  2.292208  0.041539 -1.117925  0.539058  2.843662
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025 -0.615290
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822 -1.034542

In [24]:
df3.drop('Add', axis=1)

col1      col2      col3      col4      col5
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822

In [25]:
df3

col1      col2      col3      col4      col5       Add
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436 -0.473025
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008 -0.338866
row3  0.551454  2.292208  0.041539 -1.117925  0.539058  2.843662
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025 -0.615290
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822 -1.034542

Removing Columns

In [26]:
df3.drop('Add',axis=1,inplace=True)
df3

col1      col2      col3      col4      col5
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822

In [27]:
df3.drop('row1', axis=0)

col1      col2      col3      col4      col5
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025
row5 -0.878108 -0.156434  0.256570 -0.988779 -0.338822

Removing Rows

In [28]:
df3.drop('row5',axis=0,inplace=True)
df3

col1      col2      col3      col4      col5
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025

In [29]:
df3.loc['row1']

col1   -0.416758
col2   -0.056267
col3   -2.136196
col4    1.640271
col5   -1.793436
Name: row1, dtype: float64

In [30]:
df3.loc[:,'col2']

row1   -0.056267
row2    0.502881
row3    2.292208
row4   -0.019130
Name: col2, dtype: float64

In [31]:
df3

col1      col2      col3      col4      col5
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008
row3  0.551454  2.292208  0.041539 -1.117925  0.539058
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025

In [32]:
df3.iloc[:,1]

row1   -0.056267
row2    0.502881
row3    2.292208
row4   -0.019130
Name: col2, dtype: float64

In [33]:
df3.iloc[:,1:4]

col2      col3      col4
row1 -0.056267 -2.136196  1.640271
row2  0.502881 -1.245288 -1.057952
row3  2.292208  0.041539 -1.117925
row4 -0.019130  1.175001 -0.747871

In [34]:
df3.loc['row1',['col1','col2']]

col1   -0.416758
col2   -0.056267
Name: row1, dtype: float64

In [35]:
df3.iloc[2,1:6]


col2    2.292208
col3    0.041539
col4   -1.117925
col5    0.539058
Name: row3, dtype: float64

In [36]:
df3['Add']=df3['col1']+df3['col2']
df3

col1      col2      col3      col4      col5       Add
row1 -0.416758 -0.056267 -2.136196  1.640271 -1.793436 -0.473025
row2 -0.841747  0.502881 -1.245288 -1.057952 -0.909008 -0.338866
row3  0.551454  2.292208  0.041539 -1.117925  0.539058  2.843662
row4 -0.596160 -0.019130  1.175001 -0.747871  0.009025 -0.615290

Missing Data

In [39]:
df1=pd.DataFrame({'A':[1,2,np.nan],
                 'B':[np.nan,np.nan,1],
                  'C':[1,np.nan,2]})
df1

A    B    C
0  1.0  NaN  1.0
1  2.0  NaN  NaN
2  NaN  1.0  2.0

In [42]:
df1.isna()

A      B      C
0  False   True  False
1  False   True   True
2   True  False  False

In [44]:
df1.isna().sum()

A    1
B    2
C    1
dtype: int64

In [50]:
df1.dropna() #removing of NaN values

Empty DataFrame
Columns: [A, B, C]
Index: []

In [53]:
df1.fillna(value=2)

A    B    C
0  1.0  2.0  1.0
1  2.0  2.0  2.0
2  2.0  1.0  2.0

In [54]:
df1['A'].fillna(value=df1['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [58]:
df1['B'].fillna(value=df1['B'].mean())

0    1.0
1    1.0
2    1.0
Name: B, dtype: float64

In [75]:
df4=pd.DataFrame({'Company':['fb','goog','ama'],
                  'person':['sam','din','ken'],

                  'sales':[235,221,456]})
df4

Company person  sales
0      fb    sam    235
1    goog    din    221
2     ama    ken    456

In [76]:
df4.groupby('Company').mean()

<ipython-input-76-d8979878de4e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df4.groupby('Company').mean()


sales
Company       
ama      456.0
fb       235.0
goog     221.0

In [89]:
df4.groupby('Company').std()

<ipython-input-89-3264227cc67b>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df4.groupby('Company').std()


sales
Company       
ama        NaN
fb         NaN
goog       NaN

In [90]:
fd=df4.groupby('Company')

In [94]:
fd.min()

person  sales
Company              
ama        ken    456
fb         sam    235
goog       din    221

In [93]:
fd.max()

person  sales
Company              
ama        ken    456
fb         sam    235
goog       din    221

In [97]:
fd.count()

person  sales
Company               
ama           1      1
fb            1      1
goog          1      1

In [98]:
fd.describe()

sales                                              
        count   mean std    min    25%    50%    75%    max
Company                                                    
ama       1.0  456.0 NaN  456.0  456.0  456.0  456.0  456.0
fb        1.0  235.0 NaN  235.0  235.0  235.0  235.0  235.0
goog      1.0  221.0 NaN  221.0  221.0  221.0  221.0  221.0